# Generated by Django 2.0.2 on 2018-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20180302_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='pics/None/no_cover.png', upload_to='pics/'),
        ),
    ]
